version: '1.0'

services:
  mongo:
    image: mongo
    restart: always
    container_name: tesis-mongodb
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - data_tesis:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js

  mongo-express:
    image: mongo-express
    restart: always
    container_name: tesis-mongoexpress
    ports:
      - ${DB_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/

volumes:
  data_tesis:
